Task 2
Soolamis/itra_react_exe_client pull request #5
Opened 2020-09-07 07:52 UTC by Soolamis

2020-09-08 15:48 UTC, dHihich commented
package-lock.json should be under source control

2020-09-08 15:56 UTC, dHihich commented
loader is not visible on small screen sizes (need to scroll down to see loader)

2020-09-08 17:11 UTC, dHihich requested changes

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/ColumnVisibility.tsx
> +export default function ColumnVisibillity({
bad name

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/ColumnVisibilityIcon.tsx
> +export default function ColumnVisibility({
bad name

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/ColumnVisibilityIcon.tsx
> +export default function ColumnVisibility({
I don't see much sense doing it a separate component 'cause this component is pretty straightforward. If you'd like to make it a separate component, you could place it in ColumnVisibility component

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/ColumnVisibility.tsx
> +    visible: Array<types.Columns>;
`visible` - not obvious name. Should be more descriptive

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/DataTable.tsx
> +                Toolbar: props => (
please extract a new component

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/index.ts
> +import DataTable from './DataTableContainer'
You export DataTableContainer as a DataTable but you have DataTable component. It's confusing

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/DataTableContainer.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(DataTable);
personally I don't like an approach with containers
Look, you connect DataTableContainer to redux store and now you have to pass all data as props into nested components. Even in this simple example you already have pretty deep hierarchy of components: `DataTable -> ColumnVisibility ->ColumnVisibilityDialog -> ControlColumnVisibility`. Some components in this chain don't really need all the props you pass, they have them just to pass it deeper to the components which really need these props.  Firstly it makes code not as readable as it could be. Secondly it might lead to undesired re-renders and as a result to performance issues. Please have a look at this recommendation from oficial docs - https://redux.js.org/style-guide/style-guide#connect-more-components-to-read-data-from-the-store

btw, you can go through all items on this page https://redux.js.org/style-guide/style-guide. It should be helpful

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/DataTableContainer.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(DataTable);
I'd recommend refactor this piece by connecting intermediate component to the store rather than pass all the props from the top component

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/DataTableContainer.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(DataTable);
What do you think?

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/DataTable.tsx
> +export const columnsLocalizations = new Map<types.Columns, string>([
I think localization should be moved out of this component. Should be a separate file

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/DataTable.tsx
> +interface modifier {
it should be uppercase, shouldn't it?

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/DataTable.tsx
> +function modifyColumnList(columns: Array<Column>): Array<Column> {
a lot of functions which do not look like a part of this component. Should be refactored in regards of single responsibility principle

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/ColumnVisibilityDialog.tsx
> +            setVisibleColumns([
looks like this hook might make code better - https://github.com/immerjs/use-immer

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/ColumnVisibilityControl.tsx
> +export default function ColumnVisibilityControlProps({
wrong name

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/ColumnVisibilityControl.tsx
> +export default function ColumnVisibilityControlProps({
please provide better names for your components. They should be descriptive enough to understand purpose and responsibility of the component. ColumnVilibility - bad name. ColumnVisibilityControl - not too descriptive as well. I'd call these components like ColumnsSelector, ColumnsSelectorDialog, ColumnsCheckboxList or something like this

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/reducer/reducer.ts
> +    visibleColumns: [
better to keep this in separate constants file alongside with page sizes, default page size, etc.

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/reducer/reducer.ts
> +        setVisibilityColumns(
setColumnsVisibility?

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/reducer/reducer.ts
> +        if(response.ok) {
what will happen if server responds with 500?

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/reducer/reducer.ts
> +}
no state field for data fetch error

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/reducer/reducer.ts
> +        )
no action for *.rejected case

2020-09-08 17:11 UTC, dHihich commented on src/features/dataTable/ColumnVisibility.test.tsx
> +test('', () => {
tests without names

2020-09-09 05:18 UTC, Soolamis commented on src/features/dataTable/DataTableContainer.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(DataTable);
Actually, write with containers little bit painfully. I'll refactor this without container and connect function and use hooks from react-redux

2020-10-06 08:10 UTC, merged